version: '3.7'

services:
  logisat-db:
    image: postgres
    container_name: logisat-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: logisat_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: welcome1

  web-client:
    build:
      dockerfile: Dockerfile
    container_name: web-client
    ports:
      - '3000:3000'
    environment:
      PROFILE: dev-docker
      JAVA_OPTS: -Xmx1G
    depends_on:
      - logisat-db
